spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_wallet
    username: Stock_DB
    password: Stock1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080