spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stock_wallet
    username: admin
    password: 54321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080